spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${app.db.host}:${app.db.port}/vote?currentSchema=voices
    driver-class-name: org.postgresql.Driver

server:
  port: 80

app:
  db:
    host: localhost
    port: 5432

error:
  include-message: ALWAYS
  include-stacktrace: NEVER